// <auto-generated />
using System;
using AccountingEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace accounting_api.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    partial class AccountingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_code");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.JournalEntryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Credit")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("credit");

                    b.Property<decimal>("Debit")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("debit");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entry_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_journal_entry_lines_account_id");

                    b.HasIndex("TransactionId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_entry_lines_transaction_id_sequence");

                    b.ToTable("journal_entry_lines", null, t =>
                        {
                            t.HasCheckConstraint("chk_debit_xor_credit", "(debit > 0 AND credit = 0) OR (credit > 0 AND debit = 0)");
                        });
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.SourceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsManualEntryAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manual_entry_allowed");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_source_rules");

                    b.HasIndex("SourceType")
                        .IsUnique()
                        .HasDatabaseName("ix_source_rules_source_type");

                    b.ToTable("source_rules", (string)null);
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.SourceRuleLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AmountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("amount_type");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("entry_type");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("SourceRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_rule_id");

                    b.HasKey("Id")
                        .HasName("pk_source_rule_lines");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_source_rule_lines_account_id");

                    b.HasIndex("SourceRuleId")
                        .HasDatabaseName("ix_source_rule_lines_source_rule_id");

                    b.ToTable("source_rule_lines", (string)null);
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("PostedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("posted_at");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("PostedAt")
                        .HasDatabaseName("ix_transactions_posted_at");

                    b.HasIndex("Reference")
                        .HasDatabaseName("ix_transactions_reference");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.JournalEntryLine", b =>
                {
                    b.HasOne("AccountingEngine.Core.Domain.Entities.Account", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entry_lines_accounts_account_id");

                    b.HasOne("AccountingEngine.Core.Domain.Entities.Transaction", "Transaction")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_journal_entry_lines_transactions_transaction_id");

                    b.Navigation("Account");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.SourceRuleLine", b =>
                {
                    b.HasOne("AccountingEngine.Core.Domain.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_source_rule_lines_accounts_account_id");

                    b.HasOne("AccountingEngine.Core.Domain.Entities.SourceRule", "SourceRule")
                        .WithMany("Lines")
                        .HasForeignKey("SourceRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_rule_lines_source_rules_source_rule_id");

                    b.Navigation("Account");

                    b.Navigation("SourceRule");
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.Account", b =>
                {
                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.SourceRule", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("AccountingEngine.Core.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("JournalEntryLines");
                });
#pragma warning restore 612, 618
        }
    }
}
